[package]
name = "rust-iam"
version = "0.1.1"
edition = "2021"

[dependencies]
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
wildcard = "0.3.0"
matches-macro = {path = "./matches-macro"}
